### SIGN UP
POST http://localhost:8080/api/auth/sign-up
Content-Type: application/json

{
  "username": "lagovchina",
  "password": "123123"
}

### SIGN IN
POST http://localhost:8080/api/auth/sign-in
Content-Type: application/json

{
  "username": "lagovchin",
  "password": "123123"
}

### SIGN OUT
POST http://localhost:8080/api/auth/sign-out

###
GET http://localhost:8080/api/resource/search?query=doc
